# This file is generated by setuptools-scm at build time.  Do not edit.
# At runtime vllm_fl/version.py imports git_version and git_date from here.
from __future__ import annotations
import re as _re

__version__: str = "0.0.0+g8a3df6354.d20260807"
version: str = __version__
_node_date: str = "2026-08-06"

_sha_m = _re.search(r"(?:^|[.+-])g(?P<sha>[0-9a-f]{7,40})(?:[.+-]|$)", __version__)
_date_m = _re.search(r"(?:^|[.+-])d(?P<ymd>\d{8})(?:[.+-]|$)", __version__)

git_version: str = _sha_m.group("sha") if _sha_m else "Unknown"
git_date: str = (
    _node_date if _node_date not in ("", "None")
    else (
        _date_m.group("ymd")[0:4] + "-" + _date_m.group("ymd")[4:6] + "-" + _date_m.group("ymd")[6:8]
        if _date_m else "Unknown"
    )
)
git_info: dict[str, str] = {"id": git_version, "date": git_date}
